### PR TITLE
Travis build on pull requests for Sia.Gateway

### PR DESCRIPTION
**Pull request by pdimitratos**
Added Travis configuration file, going to test whether this causes the correct behavior on pull requests.

### CODE REVIEW

**Comment by macrobug** [comment]
I see the build failed with:
```
The command "dotnet build .\Sia.Data.Incident.Tests\Sia.Data.Incident.Tests.csproj --configuration release" exited with 1.
$ dotnet test .\Sia.Data.Incident.Tests\Sia.Data.Incident.Tests.csproj --configuration release --logger trx --results-directory .\_temp
Switch: .Sia.Data.Incident.TestsSia.Data.Incident.Tests.csproj

```

However, since the name of the test is not mentioned anywhere in the build output, it is not clear to me whether it failed due to the failing unit test, or due to something else.

**Comment by pdimitratos** [comment]
I wonder if Travis builds on Linux machines; Zhuan was mentioning that he had to set a different option to build on Linux. I'll see what his pull request has and then try to merge it into this one and see if it helps. Otherwise, may have to dig in deeper to understand what's going on (other than 'returned 1')

**Comment by danieljurek** [comment]
If this documentation is up to be believed then we should consider xunit or nunit: 
https://docs.travis-ci.com/user/languages/csharp/#Other-test-frameworks
> Please note that the MSTest framework is not supported, as it only works on Windows/Visual Studio.

.. Fortunately switching to xunit is a matter of renaming the attributes and changing some namespaces. xunit has visual studio support and is pretty easy to get working in windows/linux environments.

https://xunit.github.io/

**Comment by pdimitratos** [comment]
Latest attempt (with the paths to the test .csproj files hardcoded and separate dotnet test calls for each test project) was successful! The canary I added died as expected (the Sia.Gateway.Tests.FailingTestForTravisConfirmation.FailSoTravisBuildFails() test failed and confirmed that this causes the travis build to block).

Next step is to remove that test and confirm that build succeeds (with tests run)

**Comment by pdimitratos** [comment]
@macrobug @danieljurek 

I looked up the command for running tests and realized that I had been doing it wrong. This version runs the tests and passes/fails based on test results (on the Travis Linux agent no less!)

Anyone able to review and approve?

**Comment by strand** [comment]
4 commits to 3 lines changed!

**Pull request merged**
